проверка пересборки

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,13 +1,9 @@
 name: Lint
 
 on:
- # Trigger the workflow on push or pull request,
-  # but only for the main branch
   push:
     branches:
       - main
-  # Replace pull_request with pull_request_target if you
-  # plan to use this action with forks, see the Limitations section
   pull_request:
     branches:
       - main
@@ -18,21 +14,53 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-      - run: npm ci
-      - run: npm run lint
+      - name: Install dependencies
+        run: npm ci
+      - name: Run linter
+        run: npm run lint
+      - name: Check for linter errors
+        id: check-linter-errors
+        if: always()
+        run: |
+          # Check if linter found any errors
+          if [ -n "$(npm run lint --silent | grep 'error')" ]; then
+            echo "Linter errors found"
+            exit 1
+          fi
+      - name: Rebuild project
+        if: always()
+        run: npm run build
 
   run-linters-fix:
     name: Run linters and fix issues
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-      - run: npm ci
-      - run: npm run lint:fix
+      - name: Install dependencies
+        run: npm ci
+      - name: Run linter and fix issues
+        run: npm run lint:fix
+      - name: Check if linter errors still exist
+        id: check-linter-errors
+        if: always()
+        run: |
+          # Check if linter found any errors
+          if [ -n "$(npm run lint --silent | grep 'error')" ]; then
+            echo "Linter errors still found after fixing"
+            exit 1
+          fi
+      - name: Rebuild project
+        if: always()
+        run: npm run build
